server:
  port: 8080

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: bigdata123

logging:
  level:
    root: debug
    org.springframework.web: debug
    org.springframework.security: debug
