server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #eureka服务注册地址
spring:
  application:
    name: config-server
  cloud: #git管理配置
    config:
      server:
        git:
          uri: https://github.com/xyzmonday/cloud-config-sample #git仓库地址
          searchPaths: /
          username: xyzmonday
          password: yff3445683
      label: master
rabbitmq:
  addresses: amqp://localhost:5672
  username: guest
  password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"
