spring:
  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 3600000ms
  redis:
    host: localhost
    port: 6379
    database: 0
    password: bigdata123
logging:
  level:
    root: info