server:
  port: 8761  # 当前eureka server 服务的端口号为8080
eureka:
  instance:
    hostname: localhost # 当前eureka 的hostname 为 localhost
  client:
    register-with-eureka: false # 当前服务不需要到eureka server上注册为客户端
    fetch-registry: false #
    serviceUrl: # eureka服务地址
      defaultZone: http://localhost:${server.port}/eureka/
spring:
  application:
    name: eureka-server