server:
  port: 9411
spring:
  application:
    name: zipkin-server
  sleuth:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: yff3445683
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    schema[0]: classpath:/zipkin.sql
    continue-on-error: true
management:
  metrics:
    web:
      server:
        auto-time-requests: false
zipkin:
  collector:
    rabbitmq:
      addresses: localhost:5672
      password: guest
      username: guest
      queue: zipkin
  storage:
    StorageComponent: mysql
    type: mysql

