eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8093
spring:
  application:
    name: zipkin-client-two
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  sleuth:
    sampler:
      probability: 1.0
    zipkin:
      base-url: http://localhost:9411
      rabbitmq:
        queue: zipkin
feign:
  hystrix:
    enabled: true